language: python

python:
  - "3.4"
  - "3.5"

# install codecov
before_install:
  - sudo apt-get update
  - sudo apt-get install npm
  - pip install codecov

# command to install dependencies
install:
  - sudo npm install
  - pip install -r requirements.txt

# command to run tests
script:
  - npm test
  - coverage run run_tests.py

after_success:
  - codecov